
default: &default
  adapter: postgresql
  database: ddkeu32m7p1j5j
  username: vcfxclzapdxjnz
  password: weickum23
  pool: 5
  timeout: 5000

development:
  <<: *default



test:
  <<: *default


production:
  <<: *default
