
default: &default
  adapter: postgresql
  database: todo
  username: postgres
  password: weickum23
  pool: 5
  timeout: 5000

development:
  <<: *default



test:
  <<: *default


production:
  <<: *default
