
default: &default
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
  pool: 5
  timeout: 5000

development:
  <<: *default



test:
  <<: *default


production:
  <<: *default
